### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by farnaf** [lbryton/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] #2
  - please format all terminal commands as code
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [ ] Last example counts keystrokes and shows how to run remotely saving time
  - please make sure the last step covers this section from lab 1: use what you’ve learned to come up with the most pleasant process you can for making a local edit to WhereAmI.java, then copying it to the remote server and running it.
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
nice job 😃
feel free to comment below any questions related to the rubric/feedback!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by lbryton** [comment]
Hello, I am not sure what exactly you mean by those two issues. Could you give me an example so I could fix it?
Thanks!

**Comment by lbryton** [comment]
I found out how to fix the issues and requested a regrade.

**Comment by farnaf** [comment]
Hi there! Thanks for making the new fixes. The second to last checkpoint is not quite complete yet. The method you came up with is great (and very close to what we're looking for), but it's not running **remotely**. The goal of the last step is to use the command in your local terminal (not from your 15L account) but still be able to get the same output you get right now: 

Linux
cs15lwi22aaz
...

Let me know if you have any questions!
